name: Update Dashboard

on:
  schedule:
    - cron: '0 6 * * *'   # daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'


    - name: Install dependencies
      run: pip install requests groq

    - name: Run script
      run: python script.py
      env:
       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}


    - name: Commit changes
      run: |
        git config --global user.name "Sujaicodes"
        git config --global user.email "sujaishukla55555@gmail.com"
        git pull
        git add .
        git commit -m "Auto update dashboard" || echo "No changes"
        git push
